[project]
name = "polars-datafusion-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datafusion>=49.0.0",
    "numpy>=2.3.2",
    "polars>=1.33.0",
]
